// Includes.
#include    <a_samp>
#include    <includes\tlou>
#include    <includes\projectiles>
#include    <includes\PathFinder>

// Dependencies.
#include    <audio>

#include    <YSI\y_bit>
#include    <YSI\y_dialog>
#include    <YSI\y_iterate>
#include    <YSI\y_timers>
#include    <YSI\y_stringhash>
#include    <YSI\y_commands>
#include    <YSI\y_inline>

#include    <a_mysql>
#include    <sscanf2>
#include    <YSF>
#include    <PawnPlus>
#include    <log-plugin>
#include    <colour-manipulation>
#include    <streamer>
#include    <FCNPC>
#include    <a_mysql_yinline>
#include    <bcrypt>

// Tests.
#include    <utils\testsounds>

// Modules.
#include    <config\main>
#include    <utils\main>
#include    <utils\3DTryg\main>
#include    <TLoU.animations\main>
#include    <TLoU.audio\main>
#include    <TLoU.backpack\main>
#include    <TLoU.backpack\crafting\main>
#include    <TLoU.backpack\skills\main>
#include    <TLoU.backpack\collectibles\main>
#include    <TLoU.chat\main>
#include    <TLoU.players\main>
#include    <TLoU.players\statuses\main>
#include    <TLoU.players\damages\main>
#include    <TLoU.fire\main>
#include    <TLoU.health\main>
#include    <TLoU.hud\main>
#include    <TLoU.dbQueries\main>
#include    <TLoU.dialogs\main>
#include    <TLoU.items\main>
#include    <TLoU.items\sprites\main>
#include    <TLoU.npcs\main>
#include    <TLoU.npcs\animations\main>
#include    <TLoU.npcs\damages\main>
#include    <TLoU.npcs\movement\main>
#include    <TLoU.npcs\statuses\main>
#include    <TLoU.objects\main>
#include    <TLoU.registerLogin\main>
#include    <TLoU.textdraws\main>
#include    <TLoU.weaponMenu\main>
#include    <TLoU.weapons\main>
#include    <TLoU.weapons\bow\main>
#include    <TLoU.weapons\projectiles\main>
#include    <TLoU.weapons\shiv\main>
#include    <TLoU.commands\main>