forward OnPlayerBunnyHop(playerid);
forward OnPlayerCrouchBug(playerid);

forward OnPlayerFirstSpawn(playerid);
forward OnPlayerRespawn(playerid);
forward OnPlayerDie(playerid, issuerid, itemId, bodypart);

forward OnPlayerTargetPlayer(playerid, newTargetId, oldTargetId);

forward OnPlayerLookAtPlayer(playerid, lookingAt_playerId); 
forward OnPlayerLookAtNPC(playerid, lookingAt_NpcId);

forward OnPlayerGetStunned(playerid);
forward OnPlayerShakeOffStun(playerid);

forward OnPlayerGetHitByThrowable(playerid, issuerId, itemId);
forward [16]GetPlayerIpAddress(playerid);