#include	<config\natives>
#include	<config\config>
#include	<config\mysql>

#include 	<TLoU.animations\config>
#include	<TLoU.attachments\config>
#include 	<TLoU.weapons\config>
#include	<TLoU.audio\config>
#include	<TLoU.items\config>
#include 	<TLoU.backpack\config>
#include 	<TLoU.backpackCrafting\config>
#include 	<TLoU.backpackSkills\config>
#include 	<TLoU.backpackCollectibles\config>
#include	<TLoU.bow\config>
#include    <TLoU.characters\config>
#include    <TLoU.chat\config>
#include    <TLoU.commands\config>
#include    <TLoU.damages\config>
#include	<TLoU.factions\config>
#include	<TLoU.fire\config>
#include	<TLoU.health\config>
#include	<TLoU.hud\config>
#include    <TLoU.npcs\config>
#include    <TLoU.objects\config>
#include 	<TLoU.players\config>
#include 	<TLoU.playerStatuses\config>
#include 	<TLoU.projectiles\config>
#include	<TLoU.registerLogin\config>
#include  	<TLoU.textdraws\config>
#include	<TLoU.weaponMenu\config>
#include 	<TLoU.weaponsUpgrades\config>

main()
{
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " ===================================================== ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                                                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |              The Last of Us (SA-MP)               | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |   All rights reserved Copyrights to Naughty Dog   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                                                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                 Script: Riddick                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |         Models: Riddick | Website: N/A            | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                   Mapping: N/A                    | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                                                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " ===================================================== ");
}