#include    ".\modules\config\forwards.inc"
#include	".\modules\config\natives.inc"
#include	".\modules\config\config.inc"
#include	".\modules\config\mysql.inc"

#include 	".\modules\TLoU.animations\config.inc"
#include	".\modules\TLoU.audio\config.inc"
#include 	".\modules\TLoU.backpack\config.inc"
#include    ".\modules\TLoU.characters\config.inc"
#include    ".\modules\TLoU.damages\config.inc"
#include	".\modules\TLoU.factions\config.inc"
#include	".\modules\TLoU.fire\config.inc"
#include 	".\modules\TLoU.weapons\config.inc"
#include	".\modules\TLoU.items\config.inc"
#include    ".\modules\TLoU.npcs\config.inc"
#include    ".\modules\TLoU.objects\config.inc"
#include 	".\modules\TLoU.players\config.inc"
#include  	".\modules\TLoU.textdraws\config.inc"
#include	".\modules\TLoU.weaponMenu\config.inc"
#include 	".\modules\TLoU.weaponsUpgrades\config.inc"

main()
{
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " ===================================================== ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                                                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |              The Last of Us (SA-MP)               | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |   All rights reserved Copyrights to Naughty Dog   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                                                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                 Script: Riddick                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |         Models: Riddick | Website: N/A            | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                   Mapping: N/A                    | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " |                                                   | ");
	Log(eLogs[e_Log_Index][LOG_INDEX_SERVER], INFO, " ===================================================== ");
}